name: Build

on:
  push:
    branches:
      - main
      - stable
      - release

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with: 
      branch: ${{ github.ref }}

  publish-hamburg:
    needs: test
    uses: ./.github/workflows/publish.yaml
    with:
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-hamburg
      branch: ${{ github.ref_name }}
      api: https://priobike.vkw.tu-dresden.de/production/priobike-frost-mirror/FROST-Server/v1.1
      filter: "%28Datastreams%2Fproperties%2FserviceName%20eq%20%27HH_STA_traffic_lights%27%29"
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

  publish-sachsen:
    needs: test
    uses: ./.github/workflows/publish.yaml
    with:
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-sachsen
      branch: ${{ github.ref_name }}
      api: http://priobike.vkw.tu-dresden.de:20055/FROST-Server/v1.1
      filter: "%28Datastreams%2Fproperties%2FserviceName%20eq%20%27HH_STA_traffic_lights%27%29"
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}
